# Generated by Django 5.0 on 2024-01-09 19:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='your_image_folder/'), blank=True, null=True, size=5),
        ),
    ]
