# Generated by Django 5.0 on 2024-01-07 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_ordereditem_ordered_at_product_discount_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='store.product'),
        ),
    ]
