# Generated by Django 5.0 on 2024-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='store.product'),
        ),
    ]
